#pragma once
#define PMW3610_CS_PIN GP5
#define PMW3610_SCLK_PIN GP6
#define PMW3610_SDIO_PIN GP7
#define POINTING_DEVICE_ROTATION_90
#define POINTING_DEVICE_INVERT_X
#define POINTING_DEVICE_HIRES_SCROLL_ENABLE
